language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U https://github.com/platformio/platformio-core/archive/develop.zip || true
- pio settings set auto_update_platforms true
- pio settings set auto_update_libraries true
script:
- platformio run
deploy:
  provider: releases
  api_key:
    secure: $RELEASES_API_KEY
  file: ".pioenvs/d1_mini/firmware.bin"
  skip_cleanup: true
  overwrite: true
  on:
    repo: realholgi/brauknecht
    all_branches: true
